# Generated by Django 5.1 on 2024-09-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundstates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Short Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('investment_code', models.CharField(max_length=50)),
                ('investment_title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Investment Sector',
                'verbose_name_plural': 'Investment Sectors',
            },
        ),
        migrations.CreateModel(
            name='InvestmentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Short Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Contribution Slug')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Give long descriptions')),
                ('invested_on', models.DateField(null=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('investments_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmentsectors')),
                ('investments_funds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='fundstates.accountsinfo')),
            ],
            options={
                'verbose_name': 'Investment Info',
                'verbose_name_plural': 'Investments',
            },
        ),
    ]
