# Generated by Django 5.1 on 2025-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='bills_status',
            field=models.CharField(choices=[('PAID', 'Already paid'), ('AWAITING', 'Awaiting for payment'), ('PENDING', 'Pending'), ('SENT_BACK', 'Sent Back for correction')], default='PENDING', max_length=20),
        ),
    ]
