# Generated by Django 5.1 on 2024-09-29 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        ('contribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsinfo',
            name='received_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Received From'),
        ),
        migrations.AddField(
            model_name='monthlycontributioninfo',
            name='contribution_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='month', to='basics.month', verbose_name='Contribution Month'),
        ),
        migrations.AddField(
            model_name='monthlycontributioninfo',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fiscal', to='basics.fiscalyear', verbose_name='Fiscal Year'),
        ),
        migrations.AddField(
            model_name='collectionsinfo',
            name='receivable_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='contribution.monthlycontributioninfo', verbose_name='For the month'),
        ),
    ]
