# Generated by Django 5.1 on 2024-10-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsinfo',
            name='current_payment_status',
            field=models.CharField(choices=[('due', 'Dues'), ('verification', 'Verification Pending'), ('paid', 'Paid')], default='due', max_length=12),
        ),
    ]
