# Generated by Django 5.1 on 2024-10-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_alter_collectionsinfo_current_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsinfo',
            name='payment_image',
            field=models.ImageField(null=True, upload_to='images/payment', verbose_name='Picture or screenshot'),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='payment_method',
            field=models.CharField(max_length=50, null=True, verbose_name='Bank/Bkash/Card/Other'),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
    ]
