# Generated by Django 5.1 on 2024-09-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True, verbose_name='Account Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Contribution Slug')),
                ('account_no', models.CharField(max_length=100, unique=True, verbose_name='Account no')),
                ('bank_name', models.CharField(max_length=100, unique=True, verbose_name='Bank Name')),
                ('branch_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='branch_name')),
                ('bank_Code', models.CharField(max_length=50, null=True, unique=True, verbose_name='Bank Code')),
                ('routing_number', models.CharField(max_length=55, null=True, unique=True, verbose_name='Bank Routing Number')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='account current balance')),
            ],
            options={
                'verbose_name': 'Uttoron Accounts Info',
                'verbose_name_plural': 'Uttoron Accounts Info',
            },
        ),
    ]
