# Generated by Django 5.1 on 2024-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundstates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsinfo',
            name='bank_account_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='accountsinfo',
            name='account_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Account Info'),
        ),
    ]
