# Generated by Django 5.1 on 2024-09-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundstates', '0002_accountsinfo_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsinfo',
            name='account_type',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Account Type'),
        ),
    ]
